<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Infrastructure</RootNamespace>
        <AssemblyName>Aviant.Infrastructure</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CsvHelper" />

        <PackageReference Include="NetEscapades.Configuration.Yaml" />

        <PackageReference Include="Serilog.Settings.Configuration" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
      <InternalsVisibleTo Include="Aviant.Tests.Kernel.Unit" />
    </ItemGroup>

</Project>
