<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Application.Jobs</RootNamespace>
        <AssemblyName>Aviant.Application.Jobs</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Kernel\Application\Application.csproj" />
    </ItemGroup>
    
    <ItemGroup>
        <PackageReference Include="Hangfire.Core" />
    </ItemGroup>

</Project>
