<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Application.Identity</RootNamespace>
        <AssemblyName>Aviant.Application.Identity</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Kernel\Application\Application.csproj" />
        <ProjectReference Include="..\..\Persistence\Application\Application.csproj" />
        <ProjectReference Include="..\Core\Core.csproj" />
    </ItemGroup>

</Project>
