<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Infrastructure.DDD</RootNamespace>
        <AssemblyName>Aviant.Infrastructure.DDD</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="EventStore.Client" />
        <PackageReference Include="Confluent.Kafka" />
    </ItemGroup>

</Project>
