<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Application.Email</RootNamespace>
        <AssemblyName>Aviant.Application.Email</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Kernel\Application\Application.csproj" />
    </ItemGroup>

</Project>
