<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Core.Persistence</RootNamespace>
        <AssemblyName>Aviant.Core.Persistence</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Kernel\Core\Core.csproj" />
    </ItemGroup>

</Project>
