<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Core.EventSourcing</RootNamespace>
        <AssemblyName>Aviant.Core.EventSourcing</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="MediatR" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\DDD\Core\Core.csproj" />
      <ProjectReference Include="..\..\Kernel\Core\Core.csproj" />
    </ItemGroup>

</Project>
