<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Infrastructure.Jobs</RootNamespace>
        <AssemblyName>Aviant.Infrastructure.Jobs</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Hangfire.AspNetCore" />
    </ItemGroup>

</Project>
