<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>Aviant.Infrastructure.Email</RootNamespace>
        <AssemblyName>Aviant.Infrastructure.Email</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Application\Application.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" />
    </ItemGroup>

</Project>
